apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-fiber-prod
resources:
  - ../../base
namePrefix: prod-
replicas:
  - name: go-fiber-app
    count: 3
images:
  - name: your-dockerhub-username/go-fiber-app
    newTag: latest
commonLabels:
  environment: production
