all:
  children:
    dev:
      hosts:
        dev-k8s-cluster: 
          ansible_host:  localhost
          ansible_connection: local
          environment: dev
    prod:
      hosts:
        prod-k8s-cluster: 
          ansible_host: your-eks-cluster-endpoint
          ansible_connection: kubectl
          environment: prod
    monitoring:
      hosts: 
        monitoring-server:
          ansible_host: localhost
          ansible_connection: local
  vars: 
    ansible_python_interpreter:  /usr/bin/python3