apiVersion: kustomize.config.k8s.io/v1beta1
kind:  Kustomization

resources: 
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - app-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: go-fiber
      app.kubernetes.io/managed-by: kustomize
