apiVersion: v1
kind: Namespace
metadata:
  name: go-fiber-dev
  labels: 
    name: go-fiber-dev
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: go-fiber-prod
  labels:
    name: go-fiber-prod
    environment:  production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability
