apiVersion:  v1
kind: Secret
metadata:
  name: app-secrets
  namespace: go-fiber-dev
type:  Opaque
stringData: 
  DB_PASSWORD: "Postgres_Secure_2024_Pass!"
  JWT_SECRET: "MyVeryLongAndSecureJWTSecretKey2024! ChangeMeNow"
  REDIS_PASSWORD: ""
  SMTP_USERNAME: "email-server-username"
  SMTP_PASSWORD: "email-server-password"
  GOOGLE_CLIENT_SECRET: "YourRealGoogleClientSecret123"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace:  go-fiber-prod
type:  Opaque
stringData: 
  DB_PASSWORD: "CHANGE_THIS_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_THIS_IN_PRODUCTION"
  REDIS_PASSWORD:  "CHANGE_THIS_IN_PRODUCTION"
  SMTP_USERNAME: "production-smtp-username"
  SMTP_PASSWORD:  "production-smtp-password"
  GOOGLE_CLIENT_SECRET:  "ProductionGoogleClientSecret"
