apiVersion: kustomize. config.k8s.io/v1beta1
kind:  Kustomization
namespace: go-fiber-dev
resources:  
  - ../../base
namePrefix: dev-
replicas:
  - name: go-fiber-app
    count: 2
images:
  - name:  your-dockerhub-username/go-fiber-app
    newTag: dev-latest
commonLabels:
  environment: development
patchesStrategicMerge:
  - service-nodeport.yaml
