apiVersion: kustomize.config.k8s.io/v1beta1
kind:  Kustomization
resources:  
  - ../../base
namePrefix: dev-
replicas:
  - name: go-fiber-app
    count: 2
images:
  - name:  nehaghauri/go-fiber-app
    newTag: dev-latest
labels:
  - pairs:
      environment: development
patches:
  - path: service-nodeport.yaml
