apiVersion: v1
kind: Service
metadata:
  name: go-fiber-service
  namespace: go-fiber-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol:  TCP
    name: http
