---
- name: Setup Infrastructure
  hosts: localhost
  connection: local
  
  tasks:
    - name:  Initialize Terraform
      command: terraform init
      args:
        chdir: ../../terraform
    
    - name: Plan Terraform
      command: terraform plan
      args:
        chdir: ../../terraform